### ISSUE TITLE
Active Edits Date Time Bug

### ISSUE THREAD

**Issue by oefada** [wb-crowdfusion/crowdfusion-active-edits#18]
There are inconsistent date/time formats that cause issues.
We save the dates as a timestamp sometimes and mysql other times. DB field type is mysql timestamp so update all time queries accordingly.

**Comment by excelwebzone** [comment]
@oefada the is no need to use mysql unix format convert, we save the value `$this->dateFactory->newStorageDate()` (int - which is the timestamp already). So all we need is replace the use of `time()` with the same time value (see my commit)

**Comment by gdbrown** [comment]
this results in the same exact query...
`$timestamp = $this->dateFactory->newStorageDate()->toUnix() - $this->expiry;`
is equal to `$timestamp = time() - $this->expiry;`

The problem is that the table is not storing timestamps, it's mysql datetime so the query against an integer doesn't work.

the unit tests don't have coverage for the mysql repository and don't account for data that will exist that is older than the expiry.  if you load some old data, you'll see, all records are returned always.
